# Generated by Django 2.2.6 on 2019-10-23 22:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20191023_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=1),
        ),
    ]
