# Generated by Django 2.2.6 on 2019-10-24 01:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_auto_20191023_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None),
        ),
    ]
