# Generated by Django 3.0.2 on 2020-01-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_player_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=-1),
        ),
    ]
